# Workflow para fazer o build e deploy do site no GitHub Pages
name: Deploy to GitHub Pages

on:
  # Roda esse workflow sempre que houver um novo push na branch main
  push:
    branches: ["main"]

  # Permite rodar o workflow manualmente pela aba Actions do GitHub
  workflow_dispatch:

# Permissões necessárias para o deploy no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Instalar dependências
        run: npm ci
        
      - name: Fazer o Build do projeto
        run: npm run build
        
      - name: Fazer o upload do artefato (pasta dist)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
